enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  20e33ebc-fae8-4209-8110-a08455af358a: # Motoventure
    enabledByDefault: true
    hasUrls: true
    template: home
    uriFormat: __home__
type: single
